apiVersion: v1
kind: Service
metadata:
  name: myweb
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
front-deployment-patch.yaml front-deployment-patch.yaml app: myweb-fargate
    env: dev
spec:
  selector:
    app: myweb-fargate
