---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-movie-best
  region: ap-northeast-2
fargateProfiles:
  - name: myweb-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: myweb-fargate
